version: '2.1'

services:

  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017
      mem_limit: 200m

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 27000:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
      depends_on:
        - mongo
      mem_limit: 200m